version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - nback-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      # - run:
      #     name: Run tests
      #     command: stack --no-terminal test
      - run:
          name: Build executable
          command: stack --no-terminal build
      - save_cache:
          name: Cache Dependencies
          key: nback-{{ checksum "stack.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"

