version: 2.1
jobs:
  build:
    docker:
      - image: nixos/nix:2.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: nix-env -f '<nixpkgs>' -iA cabal-install wget
      - run:
          name: Build executable
          command: nix-shell --attr env release.nix --run "cabal build"
      # - run:
      #     name: Run tests
      #     command: nix-shell --attr env release.nix --run "cabal test"
